.TH "/data/home/mbreton/magrathea_raytracing/src Directory Reference" 3 "Thu Sep 2 2021" "MAGRATHEA/RAYTRACING" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_raytracing/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmagrathea\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcatalogues\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcatalogues\&.h\fP"
.br
.RI "\fISome catalogues function\&. \fP"
.ti -1c
.RI "file \fBcone\&.h\fP"
.br
.RI "\fIThree-dimensional cone\&. \fP"
.ti -1c
.RI "file \fBcreate_octree\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcreate_octree\&.h\fP"
.br
.RI "\fISome create_octree function\&. \fP"
.ti -1c
.RI "file \fBgravity\&.h\fP"
.br
.RI "\fI\fBGravity\fP cell implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBgravity2\&.h\fP"
.br
.RI "\fI\fBGravity\fP cell implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBhmaps\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhmaps\&.h\fP"
.br
.RI "\fISome hmaps function\&. \fP"
.ti -1c
.RI "file \fBinput\&.h\fP"
.br
.RI "\fI\fBInput\fP utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBintegrator\&.h\fP"
.br
.RI "\fIIntegration utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBlensing\&.h\fP"
.br
.RI "\fIIntegration utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBmiscellaneous\&.h\fP"
.br
.RI "\fISome miscellaneous function\&. \fP"
.ti -1c
.RI "file \fBobserver_velocity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobserver_velocity\&.h\fP"
.br
.RI "\fISome observer_velocity function\&. \fP"
.ti -1c
.RI "file \fBoutput\&.h\fP"
.br
.RI "\fI\fBOutput\fP utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBphoton\&.h\fP"
.br
.RI "\fI\fBPhoton\fP step implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBrays\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrays\&.h\fP"
.br
.RI "\fISome rays function\&. \fP"
.ti -1c
.RI "file \fBTReadHDF5\&.h\fP"
.br
.RI "\fIUtilities to read HDF5 files\&. \fP"
.ti -1c
.RI "file \fButility\&.h\fP"
.br
.RI "\fIList of utilities for raytracing\&. \fP"
.in -1c
