.TH "/data/home/mbreton/magrathea_raytracing Directory Reference" 3 "Wed Nov 21 2018" "MAGRATHEA/RAYTRACING" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_raytracing Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmagrathea\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcone\&.h\fP"
.br
.RI "\fIThree-dimensional cone\&. \fP"
.ti -1c
.RI "file \fBgravity\&.h\fP"
.br
.RI "\fI\fBGravity\fP cell implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBgravity2\&.h\fP"
.br
.RI "\fI\fBGravity\fP cell implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBinput\&.h\fP"
.br
.RI "\fI\fBInput\fP utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBintegrator\&.h\fP"
.br
.RI "\fIIntegration utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBmiscellaneous\&.h\fP"
.br
.RI "\fISome miscellaneous function\&. \fP"
.ti -1c
.RI "file \fBoutput\&.h\fP"
.br
.RI "\fI\fBOutput\fP utilities for raytracing\&. \fP"
.ti -1c
.RI "file \fBphoton\&.h\fP"
.br
.RI "\fI\fBPhoton\fP step implementation for raytracing\&. \fP"
.ti -1c
.RI "file \fBraytracer\&.cpp\fP"
.br
.RI "\fIMain function of the raytracer\&. \fP"
.ti -1c
.RI "file \fBTReadHDF5\&.h\fP"
.br
.RI "\fIUtilities to read HDF5 files\&. \fP"
.ti -1c
.RI "file \fButility\&.h\fP"
.br
.RI "\fIList of utilities for raytracing\&. \fP"
.in -1c
