.TH "/data/home/mbreton/magrathea_raytracing/magrathea Directory Reference" 3 "Tue Apr 6 2021" "MAGRATHEA/RAYTRACING" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_raytracing/magrathea Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaboutinstitute\&.h\fP"
.br
.RI "\fIInformation about an institution or an organization\&. \fP"
.ti -1c
.RI "file \fBaboutlicense\&.h\fP"
.br
.RI "\fIInformation about the license of a code\&. \fP"
.ti -1c
.RI "file \fBaboutobject\&.h\fP"
.br
.RI "\fIBasic about object with information on something\&. \fP"
.ti -1c
.RI "file \fBaboutpeople\&.h\fP"
.br
.RI "\fIInformation about a developer, an author, or a contributor\&. \fP"
.ti -1c
.RI "file \fBabstractaboutobject\&.h\fP"
.br
.RI "\fITuple abstraction of generic about object\&. \fP"
.ti -1c
.RI "file \fBabstractcontents\&.h\fP"
.br
.RI "\fITuple abstraction of numerical simulation contents\&. \fP"
.ti -1c
.RI "file \fBabstracthypercube\&.h\fP"
.br
.RI "\fIAbstract function provider for n-dimensional cubes\&. \fP"
.ti -1c
.RI "file \fBabstracthypersphere\&.h\fP"
.br
.RI "\fIAbstract function provider for n-dimensional spheres\&. \fP"
.ti -1c
.RI "file \fBabstractnarray\&.h\fP"
.br
.RI "\fIAbstract base class of n-dimensional mathematical arrays\&. \fP"
.ti -1c
.RI "file \fBabstractshape\&.h\fP"
.br
.RI "\fICommon abstraction of n-dimensional shapes\&. \fP"
.ti -1c
.RI "file \fBabstractstep\&.h\fP"
.br
.RI "\fIAbstraction of an evolution step\&. \fP"
.ti -1c
.RI "file \fBabstractsubstance\&.h\fP"
.br
.RI "\fITuple abstraction of geometrical substance\&. \fP"
.ti -1c
.RI "file \fBarrayfile\&.h\fP"
.br
.RI "\fIHandler for text files representing arrays of data\&. \fP"
.ti -1c
.RI "file \fBbasefile\&.h\fP"
.br
.RI "\fIBase class for input and output with files\&. \fP"
.ti -1c
.RI "file \fBbinaryfile\&.h\fP"
.br
.RI "\fIBase class to manage generic binary files\&. \fP"
.ti -1c
.RI "file \fBconstant\&.h\fP"
.br
.RI "\fINumerical constant with constexpr constructor\&. \fP"
.ti -1c
.RI "file \fBconstants\&.h\fP"
.br
.RI "\fICommon mathematical and physical constants\&. \fP"
.ti -1c
.RI "file \fBcontents\&.h\fP"
.br
.RI "\fIBasic implementation of numerical simulation contents\&. \fP"
.ti -1c
.RI "file \fBdatahandler\&.h\fP"
.br
.RI "\fISet of basic operations on binary data related to IO\&. \fP"
.ti -1c
.RI "file \fBdatamodel\&.h\fP"
.br
.RI "\fIManagement of fundamental types representation\&. \fP"
.ti -1c
.RI "file \fBdatasize\&.h\fP"
.br
.RI "\fIWrapper of binary data size and manager of unit conversion\&. \fP"
.ti -1c
.RI "file \fBeuleriancategory\&.h\fP"
.br
.RI "\fICategory concept of eulerian : data at a fixed position\&. \fP"
.ti -1c
.RI "file \fBevolution\&.h\fP"
.br
.RI "\fIResizable container of steps dedicated to integration\&. \fP"
.ti -1c
.RI "file \fBfilelist\&.h\fP"
.br
.RI "\fIList of files based on a function or a vector\&. \fP"
.ti -1c
.RI "file \fBfilesystem\&.h\fP"
.br
.RI "\fIGlobal file management\&. \fP"
.ti -1c
.RI "file \fBfortranfile\&.h\fP"
.br
.RI "\fIHandler for binary files in fortran format\&. \fP"
.ti -1c
.RI "file \fBgridcategory\&.h\fP"
.br
.RI "\fICategory concept of grid : data related to the mesh\&. \fP"
.ti -1c
.RI "file \fBhypercube\&.h\fP"
.br
.RI "\fIN-dimensional cube\&. \fP"
.ti -1c
.RI "file \fBhypersphere\&.h\fP"
.br
.RI "\fIN-dimensional sphere\&. \fP"
.ti -1c
.RI "file \fBlagrangiancategory\&.h\fP"
.br
.RI "\fICategory concept of lagrangian : data moving with the flow\&. \fP"
.ti -1c
.RI "file \fBlogfile\&.h\fP"
.br
.RI "\fIHandler for text files representing logs\&. \fP"
.ti -1c
.RI "file \fBnamelistfile\&.h\fP"
.br
.RI "\fIHandler for text files representing lists of parameters\&. \fP"
.ti -1c
.RI "file \fBnarray\&.h\fP"
.br
.RI "\fIBasic n-dimensional mathematical array\&. \fP"
.ti -1c
.RI "file \fBshape\&.h\fP"
.br
.RI "\fIBasic implementation of shape\&. \fP"
.ti -1c
.RI "file \fBsimplehyperoctree\&.h\fP"
.br
.RI "\fIA simple hyperoctree based on bit manipulations\&. \fP"
.ti -1c
.RI "file \fBsimplehyperoctreeindex\&.h\fP"
.br
.RI "\fIA simple hyperoctree index based on an integer\&. \fP"
.ti -1c
.RI "file \fBstaticvector\&.h\fP"
.br
.RI "\fIBasic vectorized constant size container\&. \fP"
.ti -1c
.RI "file \fBstaticvectorizer\&.h\fP"
.br
.RI "\fIHelper class for generic constant size vectorization\&. \fP"
.ti -1c
.RI "file \fBstep\&.h\fP"
.br
.RI "\fIBasic implementation of an evolution step\&. \fP"
.ti -1c
.RI "file \fBsubstance\&.h\fP"
.br
.RI "\fIBasic implementation of geometrical substance\&. \fP"
.ti -1c
.RI "file \fBtemporaryfile\&.h\fP"
.br
.RI "\fITemporary file with automatic deletion at destruction\&. \fP"
.ti -1c
.RI "file \fBtextfile\&.h\fP"
.br
.RI "\fIBase class to manage generic text files\&. \fP"
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "\fIA timer to manage time measurements and benchmarks\&. \fP"
.ti -1c
.RI "file \fBvectorized\&.h\fP"
.br
.RI "\fIBasic vectorized container\&. \fP"
.ti -1c
.RI "file \fBvectorizer\&.h\fP"
.br
.RI "\fIHelper base class for generic vectorization\&. \fP"
.ti -1c
.RI "file \fBwrapper\&.h\fP"
.br
.RI "\fIBasic value wrapper with getter and setter\&. \fP"
.in -1c
