.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/aboutpeople.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/aboutpeople.h \- 
.PP
Information about a developer, an author, or a contributor\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'abstractaboutobject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "exception \fBmagrathea::AboutPeople\fP"
.br
.RI "\fIInformation about a developer, an author, or a contributor\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about a developer, an author, or a contributor\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
