.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/abstractnarray.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/abstractnarray.h \- 
.PP
Abstract base class of n-dimensional mathematical arrays\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <array>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <random>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'staticvectorizer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmagrathea::AbstractNArray< Kind, Size, Crtp, Type, Parameters >\fP"
.br
.RI "\fIAbstract base class of n-dimensional mathematical arrays\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class of n-dimensional mathematical arrays\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
