.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/constant.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/constant.h \- 
.PP
Numerical constant with constexpr constructor\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <array>\fP
.br
\fC#include <ratio>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "exception \fBmagrathea::Constant< Type, Size >\fP"
.br
.RI "\fINumerical constant with constexpr constructor\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename SelfType , unsigned int SelfSize> std::ostream & \fBmagrathea::operator<<\fP (std::ostream &lhs, const Constant< SelfType, SelfSize > &rhs)"
.br
.RI "\fI\fBOutput\fP stream operator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Numerical constant with constexpr constructor\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
