.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/fortranfile.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/fortranfile.h \- 
.PP
Handler for binary files in fortran format\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handler for binary files in fortran format\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
