.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/hypersphere.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/hypersphere.h \- 
.PP
N-dimensional sphere\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <array>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'abstractsubstance\&.h'\fP
.br
\fC#include 'abstracthypersphere\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "exception \fBmagrathea::HyperSphere< Dimension, Vector, Scalar >\fP"
.br
.RI "\fIN-dimensional sphere\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
N-dimensional sphere\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
