.TH "magrathea::Shape" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
magrathea::Shape \- 
.PP
Basic implementation of shape\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shape\&.h>\fP
.PP
Inherits \fBmagrathea::AbstractShape\fP\&.
.SS "Static Public Member Functions"

.PP
.RI "\fBTest\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static int \fBexample\fP ()"
.br
.RI "\fIExample function\&. \fP"
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Basic implementation of shape\&. 

This class is the direct derivation of \fBAbstractShape\fP\&. It provides the most basic and generic shape object without adding new functionalities to the abstract class\&. 
.SH "Member Function Documentation"
.PP 
.SS "int magrathea::Shape::example ()\fC [static]\fP"

.PP
Example function\&. Tests and demonstrates the use of \fBShape\fP\&. 
.PP
\fBReturns:\fP
.RS 4
0 if no error\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
