.TH "magrathea::LagrangianCategory" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
magrathea::LagrangianCategory \- 
.PP
Category concept of lagrangian : data moving with the flow\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lagrangiancategory\&.h>\fP
.SS "Static Public Member Functions"

.PP
.RI "\fBTest\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static int \fBexample\fP ()"
.br
.RI "\fIExample function\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Category concept of lagrangian : data moving with the flow\&. 

Categorizes data as an lagrangian one\&. A lagrangian data is moving with the flow : this is a way of looking at fluid motion where the observer follows an individual fluid parcel as it moves through space and time\&. 
.SH "Member Function Documentation"
.PP 
.SS "int magrathea::LagrangianCategory::example ()\fC [static]\fP"

.PP
Example function\&. Tests and demonstrates the use of \fBLagrangianCategory\fP\&. 
.PP
\fBReturns:\fP
.RS 4
0 if no error\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
