.TH "magrathea::EulerianCategory" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
magrathea::EulerianCategory \- 
.PP
Category concept of eulerian : data at a fixed position\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <euleriancategory\&.h>\fP
.SS "Static Public Member Functions"

.PP
.RI "\fBTest\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static int \fBexample\fP ()"
.br
.RI "\fIExample function\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Category concept of eulerian : data at a fixed position\&. 

Categorizes data as an eulerian one\&. An eulerian data is specified at a fixed location : this is a way of looking at a fluid motion that focuses on specific locations in the space through which the fluid flows as time passes\&. 
.SH "Member Function Documentation"
.PP 
.SS "int magrathea::EulerianCategory::example ()\fC [static]\fP"

.PP
Example function\&. Tests and demonstrates the use of \fBEulerianCategory\fP\&. 
.PP
\fBReturns:\fP
.RS 4
0 if no error\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
