.TH "/data/home/mbreton/magrathea_pathfinder/src/rays.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/rays.h \- 
.PP
Some rays function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <random>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <array>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <mpi\&.h>\fP
.br
\fC#include 'magrathea/simplehyperoctree\&.h'\fP
.br
\fC#include 'magrathea/simplehyperoctreeindex\&.h'\fP
.br
\fC#include 'magrathea/hypersphere\&.h'\fP
.br
\fC#include 'magrathea/abstracthypersphere\&.h'\fP
.br
\fC#include 'magrathea/hypercube\&.h'\fP
.br
\fC#include 'magrathea/constants\&.h'\fP
.br
\fC#include 'magrathea/evolution\&.h'\fP
.br
\fC#include 'magrathea/timer\&.h'\fP
.br
\fC#include 'cone\&.h'\fP
.br
\fC#include 'utility\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br
\fC#include 'output\&.h'\fP
.br
\fC#include 'TReadHDF5\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBparameters_t\fP"
.br
.ti -1c
.RI "class \fBRays\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBparameters_t\fP \fBparameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some rays function\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com), Michel-Andrès Breton (michel-andres.breton@obspm.fr) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013, 2015-2021 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "struct \fBparameters_t\fP  parameters"

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
