.TH "/data/home/mbreton/magrathea_pathfinder/src/magrathea/staticvector.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/magrathea/staticvector.h \- 
.PP
Basic vectorized constant size container\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'staticvectorizer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "exception \fBmagrathea::StaticVector< Type, Size >\fP"
.br
.RI "\fIBasic vectorized constant size container\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmagrathea\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic vectorized constant size container\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
