.TH "/data/home/mbreton/magrathea_pathfinder/src/TReadHDF5.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/TReadHDF5.h \- 
.PP
Utilities to read HDF5 files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <array>\fP
.br
\fC#include <random>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include 'magrathea/constants\&.h'\fP
.br
\fC#include 'hdf5\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTReadHDF5\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utilities to read HDF5 files\&. 

\fBAuthor:\fP
.RS 4
Michel-Andrès Breton (michel-andres.breton@obspm.fr) 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2021 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
