.TH "/data/home/mbreton/magrathea_pathfinder/src/utility.h" 3 "Wed Oct 6 2021" "MAGRATHEA/PATHFINDER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/data/home/mbreton/magrathea_pathfinder/src/utility.h \- 
.PP
List of utilities for raytracing\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <array>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'magrathea/hypercube\&.h'\fP
.br
\fC#include 'magrathea/hypersphere\&.h'\fP
.br
\fC#include 'cone\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "exception \fBUtility\fP"
.br
.RI "\fIList of utilities for raytracing\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
List of utilities for raytracing\&. 

\fBAuthor:\fP
.RS 4
Vincent Reverdy (vince.rev@gmail.com), Michel-Andrès Breton (michel-andres.breton@obspm.fr) 
.RE
.PP
\fBDate:\fP
.RS 4
2012-2013, 2015-2021 
.RE
.PP
\fBCopyright:\fP
.RS 4
CECILL-B License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MAGRATHEA/PATHFINDER from the source code\&.
